// Mocks generated by Mockito 5.4.6 from annotations
// in app_mobile/test/mocks/generate_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i15;

import 'package:app_mobile/core/auth/token_store.dart' as _i57;
import 'package:app_mobile/core/error/failures.dart' as _i17;
import 'package:app_mobile/features/announcements/data/datasources/announcement_remote_datasource.dart'
    as _i50;
import 'package:app_mobile/features/announcements/data/datasources/comment_remote_datasource.dart'
    as _i51;
import 'package:app_mobile/features/announcements/data/models/announcement_model.dart'
    as _i8;
import 'package:app_mobile/features/announcements/data/models/comment_model.dart'
    as _i9;
import 'package:app_mobile/features/announcements/domain/entities/announcement_entity.dart'
    as _i18;
import 'package:app_mobile/features/announcements/domain/entities/comment_entity.dart'
    as _i27;
import 'package:app_mobile/features/announcements/domain/repositories/announcement_repository.dart'
    as _i2;
import 'package:app_mobile/features/announcements/domain/repositories/comment_repository.dart'
    as _i3;
import 'package:app_mobile/features/announcements/domain/usecases/create_announcement_usecase.dart'
    as _i23;
import 'package:app_mobile/features/announcements/domain/usecases/create_comment_usecase.dart'
    as _i28;
import 'package:app_mobile/features/announcements/domain/usecases/delete_announcement_usecase.dart'
    as _i25;
import 'package:app_mobile/features/announcements/domain/usecases/delete_comment_usecase.dart'
    as _i29;
import 'package:app_mobile/features/announcements/domain/usecases/get_announcement_by_id_usecase.dart'
    as _i20;
import 'package:app_mobile/features/announcements/domain/usecases/get_announcements_by_creator_usecase.dart'
    as _i22;
import 'package:app_mobile/features/announcements/domain/usecases/get_announcements_by_priority_usecase.dart'
    as _i21;
import 'package:app_mobile/features/announcements/domain/usecases/get_announcements_usecase.dart'
    as _i14;
import 'package:app_mobile/features/announcements/domain/usecases/get_comments_usecase.dart'
    as _i26;
import 'package:app_mobile/features/announcements/domain/usecases/update_announcement_usecase.dart'
    as _i24;
import 'package:app_mobile/features/company/data/datasources/company_remote_datasource.dart'
    as _i54;
import 'package:app_mobile/features/company/data/models/company_model.dart'
    as _i12;
import 'package:app_mobile/features/company/domain/entities/company_entity.dart'
    as _i43;
import 'package:app_mobile/features/company/domain/repositories/company_repository.dart'
    as _i6;
import 'package:app_mobile/features/company/domain/usecases/create_company_usecase.dart'
    as _i42;
import 'package:app_mobile/features/company/domain/usecases/get_company_by_user_id_usecase.dart'
    as _i45;
import 'package:app_mobile/features/company/domain/usecases/update_company_usecase.dart'
    as _i44;
import 'package:app_mobile/features/events/data/datasources/event_remote_datasource.dart'
    as _i52;
import 'package:app_mobile/features/events/data/models/event_model.dart'
    as _i10;
import 'package:app_mobile/features/events/domain/entities/event_entity.dart'
    as _i31;
import 'package:app_mobile/features/events/domain/repositories/event_repository.dart'
    as _i4;
import 'package:app_mobile/features/events/domain/usecases/accept_invitation_usecase.dart'
    as _i35;
import 'package:app_mobile/features/events/domain/usecases/create_event_usecase.dart'
    as _i32;
import 'package:app_mobile/features/events/domain/usecases/decline_invitation_usecase.dart'
    as _i36;
import 'package:app_mobile/features/events/domain/usecases/delete_event_usecase.dart'
    as _i34;
import 'package:app_mobile/features/events/domain/usecases/get_events_usecase.dart'
    as _i30;
import 'package:app_mobile/features/events/domain/usecases/update_event_usecase.dart'
    as _i33;
import 'package:app_mobile/features/iam/data/datasources/iam_remote_datasource.dart'
    as _i53;
import 'package:app_mobile/features/iam/data/models/user_model.dart' as _i11;
import 'package:app_mobile/features/iam/domain/entities/user_entity.dart'
    as _i38;
import 'package:app_mobile/features/iam/domain/repositories/iam_repository.dart'
    as _i5;
import 'package:app_mobile/features/iam/domain/usecases/join_company_usecase.dart'
    as _i41;
import 'package:app_mobile/features/iam/domain/usecases/sign_in_usecase.dart'
    as _i37;
import 'package:app_mobile/features/iam/domain/usecases/sign_out_usecase.dart'
    as _i40;
import 'package:app_mobile/features/iam/domain/usecases/sign_up_usecase.dart'
    as _i39;
import 'package:app_mobile/features/profile/data/datasources/profile_remote_datasource.dart'
    as _i55;
import 'package:app_mobile/features/profile/data/models/profile_model.dart'
    as _i13;
import 'package:app_mobile/features/profile/domain/entities/profile_entity.dart'
    as _i47;
import 'package:app_mobile/features/profile/domain/repositories/profile_repository.dart'
    as _i7;
import 'package:app_mobile/features/profile/domain/usecases/get_company_members_usecase.dart'
    as _i49;
import 'package:app_mobile/features/profile/domain/usecases/get_profile_usecase.dart'
    as _i46;
import 'package:app_mobile/features/profile/domain/usecases/update_profile_usecase.dart'
    as _i48;
import 'package:fpdart/fpdart.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i19;
import 'package:shared_preferences/src/shared_preferences_legacy.dart' as _i56;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAnnouncementRepository_0 extends _i1.SmartFake
    implements _i2.AnnouncementRepository {
  _FakeAnnouncementRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCommentRepository_1 extends _i1.SmartFake
    implements _i3.CommentRepository {
  _FakeCommentRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEventRepository_2 extends _i1.SmartFake
    implements _i4.EventRepository {
  _FakeEventRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIamRepository_3 extends _i1.SmartFake implements _i5.IamRepository {
  _FakeIamRepository_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCompanyRepository_4 extends _i1.SmartFake
    implements _i6.CompanyRepository {
  _FakeCompanyRepository_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileRepository_5 extends _i1.SmartFake
    implements _i7.ProfileRepository {
  _FakeProfileRepository_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAnnouncementModel_6 extends _i1.SmartFake
    implements _i8.AnnouncementModel {
  _FakeAnnouncementModel_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCommentModel_7 extends _i1.SmartFake implements _i9.CommentModel {
  _FakeCommentModel_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEventModel_8 extends _i1.SmartFake implements _i10.EventModel {
  _FakeEventModel_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserModel_9 extends _i1.SmartFake implements _i11.UserModel {
  _FakeUserModel_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCompanyModel_10 extends _i1.SmartFake implements _i12.CompanyModel {
  _FakeCompanyModel_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileModel_11 extends _i1.SmartFake implements _i13.ProfileModel {
  _FakeProfileModel_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetAnnouncementsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAnnouncementsUseCase extends _i1.Mock
    implements _i14.GetAnnouncementsUseCase {
  MockGetAnnouncementsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AnnouncementRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAnnouncementRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AnnouncementRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, List<_i18.AnnouncementEntity>>> call({
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#forceRefresh: forceRefresh}),
            returnValue:
                _i15.Future<
                  _i16.Either<_i17.Failure, List<_i18.AnnouncementEntity>>
                >.value(
                  _i19.dummyValue<
                    _i16.Either<_i17.Failure, List<_i18.AnnouncementEntity>>
                  >(
                    this,
                    Invocation.method(#call, [], {#forceRefresh: forceRefresh}),
                  ),
                ),
          )
          as _i15.Future<
            _i16.Either<_i17.Failure, List<_i18.AnnouncementEntity>>
          >);
}

/// A class which mocks [GetAnnouncementByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAnnouncementByIdUseCase extends _i1.Mock
    implements _i20.GetAnnouncementByIdUseCase {
  MockGetAnnouncementByIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AnnouncementRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAnnouncementRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AnnouncementRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, _i18.AnnouncementEntity>> call(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue:
                _i15.Future<
                  _i16.Either<_i17.Failure, _i18.AnnouncementEntity>
                >.value(
                  _i19.dummyValue<
                    _i16.Either<_i17.Failure, _i18.AnnouncementEntity>
                  >(this, Invocation.method(#call, [id])),
                ),
          )
          as _i15.Future<_i16.Either<_i17.Failure, _i18.AnnouncementEntity>>);
}

/// A class which mocks [GetAnnouncementsByPriorityUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAnnouncementsByPriorityUseCase extends _i1.Mock
    implements _i21.GetAnnouncementsByPriorityUseCase {
  MockGetAnnouncementsByPriorityUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AnnouncementRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAnnouncementRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AnnouncementRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, List<_i18.AnnouncementEntity>>> call(
    String? priority,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [priority]),
            returnValue:
                _i15.Future<
                  _i16.Either<_i17.Failure, List<_i18.AnnouncementEntity>>
                >.value(
                  _i19.dummyValue<
                    _i16.Either<_i17.Failure, List<_i18.AnnouncementEntity>>
                  >(this, Invocation.method(#call, [priority])),
                ),
          )
          as _i15.Future<
            _i16.Either<_i17.Failure, List<_i18.AnnouncementEntity>>
          >);
}

/// A class which mocks [GetAnnouncementsByCreatorUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAnnouncementsByCreatorUseCase extends _i1.Mock
    implements _i22.GetAnnouncementsByCreatorUseCase {
  MockGetAnnouncementsByCreatorUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AnnouncementRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAnnouncementRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AnnouncementRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, List<_i18.AnnouncementEntity>>> call(
    String? createdBy,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [createdBy]),
            returnValue:
                _i15.Future<
                  _i16.Either<_i17.Failure, List<_i18.AnnouncementEntity>>
                >.value(
                  _i19.dummyValue<
                    _i16.Either<_i17.Failure, List<_i18.AnnouncementEntity>>
                  >(this, Invocation.method(#call, [createdBy])),
                ),
          )
          as _i15.Future<
            _i16.Either<_i17.Failure, List<_i18.AnnouncementEntity>>
          >);
}

/// A class which mocks [CreateAnnouncementUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateAnnouncementUseCase extends _i1.Mock
    implements _i23.CreateAnnouncementUseCase {
  MockCreateAnnouncementUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AnnouncementRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAnnouncementRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AnnouncementRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, _i18.AnnouncementEntity>> call({
    required String? title,
    required String? description,
    String? image,
    required String? priority,
    required String? createdBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #title: title,
              #description: description,
              #image: image,
              #priority: priority,
              #createdBy: createdBy,
            }),
            returnValue:
                _i15.Future<
                  _i16.Either<_i17.Failure, _i18.AnnouncementEntity>
                >.value(
                  _i19.dummyValue<
                    _i16.Either<_i17.Failure, _i18.AnnouncementEntity>
                  >(
                    this,
                    Invocation.method(#call, [], {
                      #title: title,
                      #description: description,
                      #image: image,
                      #priority: priority,
                      #createdBy: createdBy,
                    }),
                  ),
                ),
          )
          as _i15.Future<_i16.Either<_i17.Failure, _i18.AnnouncementEntity>>);
}

/// A class which mocks [UpdateAnnouncementUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateAnnouncementUseCase extends _i1.Mock
    implements _i24.UpdateAnnouncementUseCase {
  MockUpdateAnnouncementUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AnnouncementRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAnnouncementRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AnnouncementRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, _i18.AnnouncementEntity>> call({
    required String? id,
    required String? title,
    required String? description,
    String? image,
    required String? priority,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #id: id,
              #title: title,
              #description: description,
              #image: image,
              #priority: priority,
            }),
            returnValue:
                _i15.Future<
                  _i16.Either<_i17.Failure, _i18.AnnouncementEntity>
                >.value(
                  _i19.dummyValue<
                    _i16.Either<_i17.Failure, _i18.AnnouncementEntity>
                  >(
                    this,
                    Invocation.method(#call, [], {
                      #id: id,
                      #title: title,
                      #description: description,
                      #image: image,
                      #priority: priority,
                    }),
                  ),
                ),
          )
          as _i15.Future<_i16.Either<_i17.Failure, _i18.AnnouncementEntity>>);
}

/// A class which mocks [DeleteAnnouncementUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteAnnouncementUseCase extends _i1.Mock
    implements _i25.DeleteAnnouncementUseCase {
  MockDeleteAnnouncementUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AnnouncementRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAnnouncementRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AnnouncementRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, _i16.Unit>> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue:
                _i15.Future<_i16.Either<_i17.Failure, _i16.Unit>>.value(
                  _i19.dummyValue<_i16.Either<_i17.Failure, _i16.Unit>>(
                    this,
                    Invocation.method(#call, [id]),
                  ),
                ),
          )
          as _i15.Future<_i16.Either<_i17.Failure, _i16.Unit>>);
}

/// A class which mocks [GetCommentsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCommentsUseCase extends _i1.Mock
    implements _i26.GetCommentsUseCase {
  MockGetCommentsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.CommentRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCommentRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.CommentRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, List<_i27.CommentEntity>>> call(
    String? announcementId, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #call,
              [announcementId],
              {#forceRefresh: forceRefresh},
            ),
            returnValue:
                _i15.Future<
                  _i16.Either<_i17.Failure, List<_i27.CommentEntity>>
                >.value(
                  _i19.dummyValue<
                    _i16.Either<_i17.Failure, List<_i27.CommentEntity>>
                  >(
                    this,
                    Invocation.method(
                      #call,
                      [announcementId],
                      {#forceRefresh: forceRefresh},
                    ),
                  ),
                ),
          )
          as _i15.Future<_i16.Either<_i17.Failure, List<_i27.CommentEntity>>>);
}

/// A class which mocks [CreateCommentUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateCommentUseCase extends _i1.Mock
    implements _i28.CreateCommentUseCase {
  MockCreateCommentUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.CommentRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCommentRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.CommentRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, _i27.CommentEntity>> call({
    required String? announcementId,
    required String? content,
    required String? authorId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #announcementId: announcementId,
              #content: content,
              #authorId: authorId,
            }),
            returnValue:
                _i15.Future<
                  _i16.Either<_i17.Failure, _i27.CommentEntity>
                >.value(
                  _i19.dummyValue<
                    _i16.Either<_i17.Failure, _i27.CommentEntity>
                  >(
                    this,
                    Invocation.method(#call, [], {
                      #announcementId: announcementId,
                      #content: content,
                      #authorId: authorId,
                    }),
                  ),
                ),
          )
          as _i15.Future<_i16.Either<_i17.Failure, _i27.CommentEntity>>);
}

/// A class which mocks [DeleteCommentUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteCommentUseCase extends _i1.Mock
    implements _i29.DeleteCommentUseCase {
  MockDeleteCommentUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.CommentRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCommentRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.CommentRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, _i16.Unit>> call(String? commentId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [commentId]),
            returnValue:
                _i15.Future<_i16.Either<_i17.Failure, _i16.Unit>>.value(
                  _i19.dummyValue<_i16.Either<_i17.Failure, _i16.Unit>>(
                    this,
                    Invocation.method(#call, [commentId]),
                  ),
                ),
          )
          as _i15.Future<_i16.Either<_i17.Failure, _i16.Unit>>);
}

/// A class which mocks [GetEventsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetEventsUseCase extends _i1.Mock implements _i30.GetEventsUseCase {
  MockGetEventsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.EventRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeEventRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.EventRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, List<_i31.EventEntity>>> call({
    bool? forceRefresh = false,
    String? userId,
    String? filterType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #forceRefresh: forceRefresh,
              #userId: userId,
              #filterType: filterType,
            }),
            returnValue:
                _i15.Future<
                  _i16.Either<_i17.Failure, List<_i31.EventEntity>>
                >.value(
                  _i19.dummyValue<
                    _i16.Either<_i17.Failure, List<_i31.EventEntity>>
                  >(
                    this,
                    Invocation.method(#call, [], {
                      #forceRefresh: forceRefresh,
                      #userId: userId,
                      #filterType: filterType,
                    }),
                  ),
                ),
          )
          as _i15.Future<_i16.Either<_i17.Failure, List<_i31.EventEntity>>>);
}

/// A class which mocks [CreateEventUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateEventUseCase extends _i1.Mock
    implements _i32.CreateEventUseCase {
  MockCreateEventUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.EventRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeEventRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.EventRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, _i31.EventEntity>> call({
    required String? title,
    required String? description,
    required String? date,
    required String? spaceId,
    required String? createdBy,
    required List<String>? recipientIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #title: title,
              #description: description,
              #date: date,
              #spaceId: spaceId,
              #createdBy: createdBy,
              #recipientIds: recipientIds,
            }),
            returnValue:
                _i15.Future<_i16.Either<_i17.Failure, _i31.EventEntity>>.value(
                  _i19.dummyValue<_i16.Either<_i17.Failure, _i31.EventEntity>>(
                    this,
                    Invocation.method(#call, [], {
                      #title: title,
                      #description: description,
                      #date: date,
                      #spaceId: spaceId,
                      #createdBy: createdBy,
                      #recipientIds: recipientIds,
                    }),
                  ),
                ),
          )
          as _i15.Future<_i16.Either<_i17.Failure, _i31.EventEntity>>);
}

/// A class which mocks [UpdateEventUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateEventUseCase extends _i1.Mock
    implements _i33.UpdateEventUseCase {
  MockUpdateEventUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.EventRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeEventRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.EventRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, _i31.EventEntity>> call({
    required String? id,
    required String? title,
    required String? description,
    required String? date,
    required String? spaceId,
    required List<String>? recipientIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #id: id,
              #title: title,
              #description: description,
              #date: date,
              #spaceId: spaceId,
              #recipientIds: recipientIds,
            }),
            returnValue:
                _i15.Future<_i16.Either<_i17.Failure, _i31.EventEntity>>.value(
                  _i19.dummyValue<_i16.Either<_i17.Failure, _i31.EventEntity>>(
                    this,
                    Invocation.method(#call, [], {
                      #id: id,
                      #title: title,
                      #description: description,
                      #date: date,
                      #spaceId: spaceId,
                      #recipientIds: recipientIds,
                    }),
                  ),
                ),
          )
          as _i15.Future<_i16.Either<_i17.Failure, _i31.EventEntity>>);
}

/// A class which mocks [DeleteEventUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteEventUseCase extends _i1.Mock
    implements _i34.DeleteEventUseCase {
  MockDeleteEventUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.EventRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeEventRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.EventRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, _i16.Unit>> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue:
                _i15.Future<_i16.Either<_i17.Failure, _i16.Unit>>.value(
                  _i19.dummyValue<_i16.Either<_i17.Failure, _i16.Unit>>(
                    this,
                    Invocation.method(#call, [id]),
                  ),
                ),
          )
          as _i15.Future<_i16.Either<_i17.Failure, _i16.Unit>>);
}

/// A class which mocks [AcceptInvitationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAcceptInvitationUseCase extends _i1.Mock
    implements _i35.AcceptInvitationUseCase {
  MockAcceptInvitationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.EventRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeEventRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.EventRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, _i31.EventEntity>> call(
    String? eventId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [eventId]),
            returnValue:
                _i15.Future<_i16.Either<_i17.Failure, _i31.EventEntity>>.value(
                  _i19.dummyValue<_i16.Either<_i17.Failure, _i31.EventEntity>>(
                    this,
                    Invocation.method(#call, [eventId]),
                  ),
                ),
          )
          as _i15.Future<_i16.Either<_i17.Failure, _i31.EventEntity>>);
}

/// A class which mocks [DeclineInvitationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeclineInvitationUseCase extends _i1.Mock
    implements _i36.DeclineInvitationUseCase {
  MockDeclineInvitationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.EventRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeEventRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.EventRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, _i31.EventEntity>> call(
    String? eventId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [eventId]),
            returnValue:
                _i15.Future<_i16.Either<_i17.Failure, _i31.EventEntity>>.value(
                  _i19.dummyValue<_i16.Either<_i17.Failure, _i31.EventEntity>>(
                    this,
                    Invocation.method(#call, [eventId]),
                  ),
                ),
          )
          as _i15.Future<_i16.Either<_i17.Failure, _i31.EventEntity>>);
}

/// A class which mocks [SignInUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInUseCase extends _i1.Mock implements _i37.SignInUseCase {
  MockSignInUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.IamRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeIamRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.IamRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, _i38.UserEntity>> call(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [username, password]),
            returnValue:
                _i15.Future<_i16.Either<_i17.Failure, _i38.UserEntity>>.value(
                  _i19.dummyValue<_i16.Either<_i17.Failure, _i38.UserEntity>>(
                    this,
                    Invocation.method(#call, [username, password]),
                  ),
                ),
          )
          as _i15.Future<_i16.Either<_i17.Failure, _i38.UserEntity>>);
}

/// A class which mocks [SignUpUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignUpUseCase extends _i1.Mock implements _i39.SignUpUseCase {
  MockSignUpUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.IamRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeIamRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.IamRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, void>> call({
    required String? username,
    required String? password,
    required String? name,
    required String? lastname,
    required String? email,
    List<String>? roles,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #username: username,
              #password: password,
              #name: name,
              #lastname: lastname,
              #email: email,
              #roles: roles,
            }),
            returnValue: _i15.Future<_i16.Either<_i17.Failure, void>>.value(
              _i19.dummyValue<_i16.Either<_i17.Failure, void>>(
                this,
                Invocation.method(#call, [], {
                  #username: username,
                  #password: password,
                  #name: name,
                  #lastname: lastname,
                  #email: email,
                  #roles: roles,
                }),
              ),
            ),
          )
          as _i15.Future<_i16.Either<_i17.Failure, void>>);
}

/// A class which mocks [SignOutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignOutUseCase extends _i1.Mock implements _i40.SignOutUseCase {
  MockSignOutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.IamRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeIamRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.IamRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, void>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i15.Future<_i16.Either<_i17.Failure, void>>.value(
              _i19.dummyValue<_i16.Either<_i17.Failure, void>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i15.Future<_i16.Either<_i17.Failure, void>>);
}

/// A class which mocks [JoinCompanyUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockJoinCompanyUseCase extends _i1.Mock
    implements _i41.JoinCompanyUseCase {
  MockJoinCompanyUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.IamRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeIamRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.IamRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, void>> call(String? joinCode) =>
      (super.noSuchMethod(
            Invocation.method(#call, [joinCode]),
            returnValue: _i15.Future<_i16.Either<_i17.Failure, void>>.value(
              _i19.dummyValue<_i16.Either<_i17.Failure, void>>(
                this,
                Invocation.method(#call, [joinCode]),
              ),
            ),
          )
          as _i15.Future<_i16.Either<_i17.Failure, void>>);
}

/// A class which mocks [CreateCompanyUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateCompanyUseCase extends _i1.Mock
    implements _i42.CreateCompanyUseCase {
  MockCreateCompanyUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CompanyRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCompanyRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.CompanyRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, _i43.CompanyEntity>> call({
    required String? ruc,
    required String? name,
    String? iconUrl,
    required bool? isActive,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #ruc: ruc,
              #name: name,
              #iconUrl: iconUrl,
              #isActive: isActive,
              #userId: userId,
            }),
            returnValue:
                _i15.Future<
                  _i16.Either<_i17.Failure, _i43.CompanyEntity>
                >.value(
                  _i19.dummyValue<
                    _i16.Either<_i17.Failure, _i43.CompanyEntity>
                  >(
                    this,
                    Invocation.method(#call, [], {
                      #ruc: ruc,
                      #name: name,
                      #iconUrl: iconUrl,
                      #isActive: isActive,
                      #userId: userId,
                    }),
                  ),
                ),
          )
          as _i15.Future<_i16.Either<_i17.Failure, _i43.CompanyEntity>>);
}

/// A class which mocks [UpdateCompanyUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateCompanyUseCase extends _i1.Mock
    implements _i44.UpdateCompanyUseCase {
  MockUpdateCompanyUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CompanyRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCompanyRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.CompanyRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, _i43.CompanyEntity>> call({
    required String? id,
    required String? ruc,
    required String? name,
    String? iconUrl,
    required bool? isActive,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #id: id,
              #ruc: ruc,
              #name: name,
              #iconUrl: iconUrl,
              #isActive: isActive,
            }),
            returnValue:
                _i15.Future<
                  _i16.Either<_i17.Failure, _i43.CompanyEntity>
                >.value(
                  _i19.dummyValue<
                    _i16.Either<_i17.Failure, _i43.CompanyEntity>
                  >(
                    this,
                    Invocation.method(#call, [], {
                      #id: id,
                      #ruc: ruc,
                      #name: name,
                      #iconUrl: iconUrl,
                      #isActive: isActive,
                    }),
                  ),
                ),
          )
          as _i15.Future<_i16.Either<_i17.Failure, _i43.CompanyEntity>>);
}

/// A class which mocks [GetCompanyByUserIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCompanyByUserIdUseCase extends _i1.Mock
    implements _i45.GetCompanyByUserIdUseCase {
  MockGetCompanyByUserIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CompanyRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCompanyRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.CompanyRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, _i43.CompanyEntity>> call(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [userId]),
            returnValue:
                _i15.Future<
                  _i16.Either<_i17.Failure, _i43.CompanyEntity>
                >.value(
                  _i19.dummyValue<
                    _i16.Either<_i17.Failure, _i43.CompanyEntity>
                  >(this, Invocation.method(#call, [userId])),
                ),
          )
          as _i15.Future<_i16.Either<_i17.Failure, _i43.CompanyEntity>>);
}

/// A class which mocks [GetProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProfileUseCase extends _i1.Mock implements _i46.GetProfileUseCase {
  MockGetProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.ProfileRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeProfileRepository_5(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i7.ProfileRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, _i47.ProfileEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i15.Future<
                  _i16.Either<_i17.Failure, _i47.ProfileEntity>
                >.value(
                  _i19.dummyValue<
                    _i16.Either<_i17.Failure, _i47.ProfileEntity>
                  >(this, Invocation.method(#call, [])),
                ),
          )
          as _i15.Future<_i16.Either<_i17.Failure, _i47.ProfileEntity>>);
}

/// A class which mocks [UpdateProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateProfileUseCase extends _i1.Mock
    implements _i48.UpdateProfileUseCase {
  MockUpdateProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.ProfileRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeProfileRepository_5(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i7.ProfileRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, _i47.ProfileEntity>> call(
    _i47.ProfileEntity? profile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [profile]),
            returnValue:
                _i15.Future<
                  _i16.Either<_i17.Failure, _i47.ProfileEntity>
                >.value(
                  _i19.dummyValue<
                    _i16.Either<_i17.Failure, _i47.ProfileEntity>
                  >(this, Invocation.method(#call, [profile])),
                ),
          )
          as _i15.Future<_i16.Either<_i17.Failure, _i47.ProfileEntity>>);
}

/// A class which mocks [GetCompanyMembersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCompanyMembersUseCase extends _i1.Mock
    implements _i49.GetCompanyMembersUseCase {
  MockGetCompanyMembersUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.ProfileRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeProfileRepository_5(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i7.ProfileRepository);

  @override
  _i15.Future<_i16.Either<_i17.Failure, List<_i47.ProfileEntity>>> call(
    String? companyId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [companyId]),
            returnValue:
                _i15.Future<
                  _i16.Either<_i17.Failure, List<_i47.ProfileEntity>>
                >.value(
                  _i19.dummyValue<
                    _i16.Either<_i17.Failure, List<_i47.ProfileEntity>>
                  >(this, Invocation.method(#call, [companyId])),
                ),
          )
          as _i15.Future<_i16.Either<_i17.Failure, List<_i47.ProfileEntity>>>);
}

/// A class which mocks [AnnouncementRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnnouncementRemoteDataSource extends _i1.Mock
    implements _i50.AnnouncementRemoteDataSource {
  MockAnnouncementRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.Future<List<_i8.AnnouncementModel>> getAnnouncements() =>
      (super.noSuchMethod(
            Invocation.method(#getAnnouncements, []),
            returnValue: _i15.Future<List<_i8.AnnouncementModel>>.value(
              <_i8.AnnouncementModel>[],
            ),
          )
          as _i15.Future<List<_i8.AnnouncementModel>>);

  @override
  _i15.Future<_i8.AnnouncementModel> getAnnouncementById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAnnouncementById, [id]),
            returnValue: _i15.Future<_i8.AnnouncementModel>.value(
              _FakeAnnouncementModel_6(
                this,
                Invocation.method(#getAnnouncementById, [id]),
              ),
            ),
          )
          as _i15.Future<_i8.AnnouncementModel>);

  @override
  _i15.Future<List<_i8.AnnouncementModel>> getAnnouncementsByPriority(
    String? priority,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAnnouncementsByPriority, [priority]),
            returnValue: _i15.Future<List<_i8.AnnouncementModel>>.value(
              <_i8.AnnouncementModel>[],
            ),
          )
          as _i15.Future<List<_i8.AnnouncementModel>>);

  @override
  _i15.Future<List<_i8.AnnouncementModel>> getAnnouncementsByCreator(
    String? createdBy,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAnnouncementsByCreator, [createdBy]),
            returnValue: _i15.Future<List<_i8.AnnouncementModel>>.value(
              <_i8.AnnouncementModel>[],
            ),
          )
          as _i15.Future<List<_i8.AnnouncementModel>>);

  @override
  _i15.Future<_i8.AnnouncementModel> createAnnouncement({
    required String? title,
    required String? description,
    String? image,
    required String? priority,
    required String? createdBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAnnouncement, [], {
              #title: title,
              #description: description,
              #image: image,
              #priority: priority,
              #createdBy: createdBy,
            }),
            returnValue: _i15.Future<_i8.AnnouncementModel>.value(
              _FakeAnnouncementModel_6(
                this,
                Invocation.method(#createAnnouncement, [], {
                  #title: title,
                  #description: description,
                  #image: image,
                  #priority: priority,
                  #createdBy: createdBy,
                }),
              ),
            ),
          )
          as _i15.Future<_i8.AnnouncementModel>);

  @override
  _i15.Future<_i8.AnnouncementModel> updateAnnouncement({
    required String? id,
    required String? title,
    required String? description,
    String? image,
    required String? priority,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateAnnouncement, [], {
              #id: id,
              #title: title,
              #description: description,
              #image: image,
              #priority: priority,
            }),
            returnValue: _i15.Future<_i8.AnnouncementModel>.value(
              _FakeAnnouncementModel_6(
                this,
                Invocation.method(#updateAnnouncement, [], {
                  #id: id,
                  #title: title,
                  #description: description,
                  #image: image,
                  #priority: priority,
                }),
              ),
            ),
          )
          as _i15.Future<_i8.AnnouncementModel>);

  @override
  _i15.Future<void> deleteAnnouncement(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAnnouncement, [id]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);
}

/// A class which mocks [CommentRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommentRemoteDataSource extends _i1.Mock
    implements _i51.CommentRemoteDataSource {
  MockCommentRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.Future<List<_i9.CommentModel>> getComments(String? announcementId) =>
      (super.noSuchMethod(
            Invocation.method(#getComments, [announcementId]),
            returnValue: _i15.Future<List<_i9.CommentModel>>.value(
              <_i9.CommentModel>[],
            ),
          )
          as _i15.Future<List<_i9.CommentModel>>);

  @override
  _i15.Future<_i9.CommentModel> createComment({
    required String? announcementId,
    required String? content,
    required String? authorId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createComment, [], {
              #announcementId: announcementId,
              #content: content,
              #authorId: authorId,
            }),
            returnValue: _i15.Future<_i9.CommentModel>.value(
              _FakeCommentModel_7(
                this,
                Invocation.method(#createComment, [], {
                  #announcementId: announcementId,
                  #content: content,
                  #authorId: authorId,
                }),
              ),
            ),
          )
          as _i15.Future<_i9.CommentModel>);

  @override
  _i15.Future<void> deleteComment(String? commentId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteComment, [commentId]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);
}

/// A class which mocks [EventRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventRemoteDataSource extends _i1.Mock
    implements _i52.EventRemoteDataSource {
  MockEventRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.Future<List<_i10.EventModel>> getEvents({
    String? userId,
    String? filterType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEvents, [], {
              #userId: userId,
              #filterType: filterType,
            }),
            returnValue: _i15.Future<List<_i10.EventModel>>.value(
              <_i10.EventModel>[],
            ),
          )
          as _i15.Future<List<_i10.EventModel>>);

  @override
  _i15.Future<_i10.EventModel> acceptInvitation(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#acceptInvitation, [id]),
            returnValue: _i15.Future<_i10.EventModel>.value(
              _FakeEventModel_8(
                this,
                Invocation.method(#acceptInvitation, [id]),
              ),
            ),
          )
          as _i15.Future<_i10.EventModel>);

  @override
  _i15.Future<_i10.EventModel> declineInvitation(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#declineInvitation, [id]),
            returnValue: _i15.Future<_i10.EventModel>.value(
              _FakeEventModel_8(
                this,
                Invocation.method(#declineInvitation, [id]),
              ),
            ),
          )
          as _i15.Future<_i10.EventModel>);

  @override
  _i15.Future<_i10.EventModel> createEvent({
    required String? title,
    required String? description,
    required String? date,
    required String? spaceId,
    required String? createdBy,
    required List<String>? recipientIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEvent, [], {
              #title: title,
              #description: description,
              #date: date,
              #spaceId: spaceId,
              #createdBy: createdBy,
              #recipientIds: recipientIds,
            }),
            returnValue: _i15.Future<_i10.EventModel>.value(
              _FakeEventModel_8(
                this,
                Invocation.method(#createEvent, [], {
                  #title: title,
                  #description: description,
                  #date: date,
                  #spaceId: spaceId,
                  #createdBy: createdBy,
                  #recipientIds: recipientIds,
                }),
              ),
            ),
          )
          as _i15.Future<_i10.EventModel>);

  @override
  _i15.Future<_i10.EventModel> updateEvent({
    required String? id,
    required String? title,
    required String? description,
    required String? date,
    required String? spaceId,
    required List<String>? recipientIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateEvent, [], {
              #id: id,
              #title: title,
              #description: description,
              #date: date,
              #spaceId: spaceId,
              #recipientIds: recipientIds,
            }),
            returnValue: _i15.Future<_i10.EventModel>.value(
              _FakeEventModel_8(
                this,
                Invocation.method(#updateEvent, [], {
                  #id: id,
                  #title: title,
                  #description: description,
                  #date: date,
                  #spaceId: spaceId,
                  #recipientIds: recipientIds,
                }),
              ),
            ),
          )
          as _i15.Future<_i10.EventModel>);

  @override
  _i15.Future<void> deleteEvent(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEvent, [id]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);
}

/// A class which mocks [IamRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIamRemoteDataSource extends _i1.Mock
    implements _i53.IamRemoteDataSource {
  MockIamRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.Future<_i11.UserModel> signIn(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [username, password]),
            returnValue: _i15.Future<_i11.UserModel>.value(
              _FakeUserModel_9(
                this,
                Invocation.method(#signIn, [username, password]),
              ),
            ),
          )
          as _i15.Future<_i11.UserModel>);

  @override
  _i15.Future<void> signUp({
    required String? username,
    required String? password,
    required String? name,
    required String? lastname,
    required String? email,
    List<String>? roles,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #username: username,
              #password: password,
              #name: name,
              #lastname: lastname,
              #email: email,
              #roles: roles,
            }),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> joinCompany(String? joinCode) =>
      (super.noSuchMethod(
            Invocation.method(#joinCompany, [joinCode]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);
}

/// A class which mocks [CompanyRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompanyRemoteDataSource extends _i1.Mock
    implements _i54.CompanyRemoteDataSource {
  MockCompanyRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.Future<_i12.CompanyModel> createCompany({
    required String? ruc,
    required String? name,
    String? iconUrl,
    required bool? isActive,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createCompany, [], {
              #ruc: ruc,
              #name: name,
              #iconUrl: iconUrl,
              #isActive: isActive,
              #userId: userId,
            }),
            returnValue: _i15.Future<_i12.CompanyModel>.value(
              _FakeCompanyModel_10(
                this,
                Invocation.method(#createCompany, [], {
                  #ruc: ruc,
                  #name: name,
                  #iconUrl: iconUrl,
                  #isActive: isActive,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i15.Future<_i12.CompanyModel>);

  @override
  _i15.Future<_i12.CompanyModel> updateCompany({
    required String? id,
    required String? ruc,
    required String? name,
    String? iconUrl,
    required bool? isActive,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateCompany, [], {
              #id: id,
              #ruc: ruc,
              #name: name,
              #iconUrl: iconUrl,
              #isActive: isActive,
            }),
            returnValue: _i15.Future<_i12.CompanyModel>.value(
              _FakeCompanyModel_10(
                this,
                Invocation.method(#updateCompany, [], {
                  #id: id,
                  #ruc: ruc,
                  #name: name,
                  #iconUrl: iconUrl,
                  #isActive: isActive,
                }),
              ),
            ),
          )
          as _i15.Future<_i12.CompanyModel>);

  @override
  _i15.Future<_i12.CompanyModel> getCompanyByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getCompanyByUserId, [userId]),
            returnValue: _i15.Future<_i12.CompanyModel>.value(
              _FakeCompanyModel_10(
                this,
                Invocation.method(#getCompanyByUserId, [userId]),
              ),
            ),
          )
          as _i15.Future<_i12.CompanyModel>);

  @override
  _i15.Future<_i12.CompanyModel> getCompanyById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCompanyById, [id]),
            returnValue: _i15.Future<_i12.CompanyModel>.value(
              _FakeCompanyModel_10(
                this,
                Invocation.method(#getCompanyById, [id]),
              ),
            ),
          )
          as _i15.Future<_i12.CompanyModel>);
}

/// A class which mocks [ProfileRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRemoteDataSource extends _i1.Mock
    implements _i55.ProfileRemoteDataSource {
  MockProfileRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.Future<_i13.ProfileModel> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i15.Future<_i13.ProfileModel>.value(
              _FakeProfileModel_11(this, Invocation.method(#getProfile, [])),
            ),
          )
          as _i15.Future<_i13.ProfileModel>);

  @override
  _i15.Future<_i13.ProfileModel> updateProfile(_i13.ProfileModel? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [profile]),
            returnValue: _i15.Future<_i13.ProfileModel>.value(
              _FakeProfileModel_11(
                this,
                Invocation.method(#updateProfile, [profile]),
              ),
            ),
          )
          as _i15.Future<_i13.ProfileModel>);

  @override
  _i15.Future<List<_i13.ProfileModel>> getCompanyMembers(String? companyId) =>
      (super.noSuchMethod(
            Invocation.method(#getCompanyMembers, [companyId]),
            returnValue: _i15.Future<List<_i13.ProfileModel>>.value(
              <_i13.ProfileModel>[],
            ),
          )
          as _i15.Future<List<_i13.ProfileModel>>);

  @override
  _i15.Future<List<_i13.ProfileModel>> getProfilesWithoutCompany() =>
      (super.noSuchMethod(
            Invocation.method(#getProfilesWithoutCompany, []),
            returnValue: _i15.Future<List<_i13.ProfileModel>>.value(
              <_i13.ProfileModel>[],
            ),
          )
          as _i15.Future<List<_i13.ProfileModel>>);

  @override
  _i15.Future<void> assignCompanyToUser(String? userId, String? companyId) =>
      (super.noSuchMethod(
            Invocation.method(#assignCompanyToUser, [userId, companyId]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i56.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringList, [key]))
          as List<String>?);

  @override
  _i15.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  _i15.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  _i15.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  _i15.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  _i15.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  _i15.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  _i15.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  _i15.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  _i15.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);
}

/// A class which mocks [TokenStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenStore extends _i1.Mock implements _i57.TokenStore {
  MockTokenStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasToken =>
      (super.noSuchMethod(Invocation.getter(#hasToken), returnValue: false)
          as bool);

  @override
  bool get isExpired =>
      (super.noSuchMethod(Invocation.getter(#isExpired), returnValue: false)
          as bool);

  @override
  bool get isSignedIn =>
      (super.noSuchMethod(Invocation.getter(#isSignedIn), returnValue: false)
          as bool);

  @override
  _i15.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> save(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#save, [token]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);
}
